<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Faker;

class AuthorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        $faker = \Faker\Factory::create();

        $authors = [
                array(1, '/storage/author/chit-oo-nyo.jpg', 'ချစ်ဦးညို', 'Yangon', 'authortesting@gmail.com', 'Male', '1943-04-03', 'asdfasdfasdfasdfDfadfaf'),
                array(2, '/storage/author/Stephenie_Meyer.jpg', 'Stephenie Meyer', 'Hartford, Connecticut, U.S. ', 'stepheniemeyer@gmail.com', 'Female', '1973-12-24', '<p style=\"overflow-wrap: break-word; outline: none; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(40, 40, 40); font-family: &quot;Alegreya Sans&quot;, sans-serif; font-size: 18px;\">Best known for her&nbsp;<a href=\"https://stepheniemeyer.com/the-twilight-saga/\" style=\"overflow-wrap: break-word; outline: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(106, 159, 149);\"><em style=\"overflow-wrap: break-word; outline: none;\">Twilight</em>&nbsp;series</a>, Stephenie Meyer’s four-book collection has sold over 100 million copies globally in over 50 countries, with translations in 37 different languages. Meyer was the highest-selling author of 2008 and 2009 in the United States, having sold over 29 million books in 2008, and 26.5 million books in 2009. In 2008, Meyer also released&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\"><a href=\"https://stepheniemeyer.com/portfolio/the-host-book/\" style=\"overflow-wrap: break-word; outline: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(106, 159, 149);\">The Host</a></em>, which debuted at #1 on&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\">The New York Times</em>&nbsp;and&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\">Wall Street Journal</em>&nbsp;bestseller lists. Additionally,&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\">USA Today</em>&nbsp;declared Meyer “Author of the Year,” citing that she had done something that no one else had in the 15 years of the&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\">USA Today</em>&nbsp;bestselling book list– she swept the top four slots in 2008. Meyer also accomplished this feat in 2009, when The Twilight Saga once again dominated the top of the bestseller list. All together, her books have spent over 303 weeks on the&nbsp;<em style=\"overflow-wrap: break-word; outline: none;\">New York Times</em>&nbsp;Bestseller List.</p><p style=\"overflow-wrap: break-word; outline: none; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(40, 40, 40); font-family: &quot;Alegreya Sans&quot;, sans-serif; font-size: 18px;\">Stephenie Meyer graduated from Brigham Young University with a degree in English Literature. She lives in Arizona with her husband and sons.</p>                                                                                              \r\n                                            '),
                array(3, '/storage/author/J_K_Rowling.jpg', 'J. K. Rowling', 'Yate, Gloucestershire, England ', 'jkrowling@gmail.com', 'Female', '1965-07-31', '                                             <p style=\"vertical-align: bottom; margin-right: 0px; margin-bottom: 20px; margin-left: 0px; font-size: 16px; color: rgb(77, 77, 77); font-family: proxima_nova_rgregular; background-color: rgb(242, 242, 242);\">Joanne Rowling was born on 31st July 1965 at Yate General Hospital near Bristol, and grew up in Gloucestershire in England and in Chepstow, Gwent, in south-east Wales.</p><p style=\"vertical-align: bottom; margin-right: 0px; margin-bottom: 20px; margin-left: 0px; font-size: 16px; color: rgb(77, 77, 77); font-family: proxima_nova_rgregular; background-color: rgb(242, 242, 242);\">Her father, Peter, was an aircraft engineer at the Rolls Royce factory in Bristol and her mother, Anne, was a science technician in the Chemistry department at Wyedean Comprehensive, where Jo herself went to school. Anne was diagnosed with multiple sclerosis when Jo was a teenager and died in 1990, before the Harry Potter books were published.&nbsp; Jo also has a younger sister, Di.</p><p style=\"vertical-align: bottom; margin-right: 0px; margin-bottom: 20px; margin-left: 0px; font-size: 16px; color: rgb(77, 77, 77); font-family: proxima_nova_rgregular; background-color: rgb(242, 242, 242);\">The young Jo grew up surrounded by books. “I lived for books,’’ she has said. “I was your basic common-or-garden bookworm, complete with freckles and National Health spectacles.”</p>                                                                                             \r\n                                                                                            \r\n                                            '),
                array(4, '/storage/author/E_L_James.png', 'E. L. James', 'Willesden, London, England, UK ', 'eljames@gmail.com', 'Female', '1963-03-07', '<p style=\"margin-right: 0px; margin-bottom: 26px; margin-left: 0px; padding: 0px; color: rgb(87, 87, 87); font-size: 16px;\">I’m a former TV executive, wife and mother-of-two based in the leafy suburbs of West London. I have been writing romantic fiction since 2009 and in 2012 my career took an extraordinary turn when my<em>&nbsp;Fifty Shades Trilogy&nbsp;</em>became a worldwide bestseller and subsequently a series of blockbuster movies.</p><p style=\"margin-right: 0px; margin-bottom: 26px; margin-left: 0px; padding: 0px; color: rgb(87, 87, 87); font-size: 16px;\">From an early age, I had dreamed of writing stories that readers would fall in love with—and now those dreams have come true, thanks to you guys.&nbsp; I hope that you take my new story&nbsp;<em>The Mister</em>&nbsp;to your heart just as you did&nbsp;<em>Fifty Shades.</em></p><p style=\"margin-right: 0px; margin-bottom: 26px; margin-left: 0px; padding: 0px; color: rgb(87, 87, 87); font-size: 16px;\">Thanks to all of you for your support—it has meant the world to me. If anyone were to ask me what lessons I’ve learned from my crazy adventures, I would say this: Life is not a dress rehearsal—seize the day and follow your dreams.</p><p style=\"margin-right: 0px; margin-bottom: 26px; margin-left: 0px; padding: 0px; color: rgb(87, 87, 87); font-size: 16px;\">I wish you the best of luck.</p><p style=\"margin-right: 0px; margin-bottom: 26px; margin-left: 0px; padding: 0px; color: rgb(87, 87, 87); font-size: 16px;\">EL<br>January 2019</p>                                                                                                \r\n                                            '),
                array(5, '/storage/author/Khin_Hnin_Yu.jpg', 'ခင်နှင်းယု', 'ဧရာဝတီတိုင်း ဝါးခယ်မမြို့', 'unknown@gmail.com', 'Female', '1925-09-07', '<font color=\"#0b0080\" face=\"mm3web, Myanmar Text, Myanmar3, TharLon, Noto Sans Myanmar, Masterpiece Uni Sans, Parabaik, Yunghkio, Thanlwin, Win Uni Innwa, Padauk, MyMyanmar Unicode, WinUni Innwa, Myanmar2\">ဧရာဝတီတိုင်း ဝါးခယ်မမြို့၌ အဖ အစိုးရကျောင်းဆရာကြီး ဦးဘ ၊ အမိ ဒေါ်သိန်းတင်တို့မှ ၁၉၂၅ခု ၊ စက်တင်ဘာ ရ ရက် (တနင်္လာနေ့) တွင်ဖွားမြင်သည် ။ မွေးချင်း ခုနစ်ယောက်အနက် ငါးယောက်မြောက်ဖြစ်ပြီး ဝန်ကြီးချုပ် ဦးနု နှင့်မောင်နှမ ဝမ်းကွဲတော်စပ် သူတစ်ဦးဖြစ်သည် ။ ၁၉၅ဝ တွင် ဗိုလ်ကြီးကျော်သောင်းနှင့် လက်ထပ်ခဲ့ကာ ၁၉၇ဝ တွင် ခင်ပွန်းသည် ကွယ်လွန်ခဲ့သည် ။ ၁၉၈၅ မှ ကျန်းမာရေးအလွန်ဆိုးရွားသောကြောင့် ဆေးရုံတွင် ကုသမှုခံယူ ပြီးနောက် \"ချမ်းမြေ့ရိပ်သာ\" တွင် နေထိုင်ခဲ့သည် ။ ၂၀၀၃ ဇန်နဝါရီလ ၂၁ ရက် (အင်္ဂါနေ့) နံနက် (၈:၃၀) တွင် ရန်ကုန်ပြည့်သူ့ ဆေးရုံကြီး၌ ကွယ်လွန်သည်။</font>'),
                array(6, '/storage/author/chanmyaewin.jpg', 'ချမ်းမြေ့ဝင်း', 'Yangon, Myanmar', 'chanmyaewin@gmail.com', 'Male', '1984-01-25', '<div class=\"_5aj7 _3-8j\" style=\"display: flex; margin: 12px; font-family: system-ui, -apple-system, system-ui, &quot;.SFNSText-Regular&quot;, sans-serif; color: rgb(28, 30, 33); font-size: 12px;\"><div class=\"_4bl9\" style=\"overflow-wrap: break-word; overflow: hidden; flex: 1 0 0px; font-family: inherit;\"><div class=\"_3-8w\" style=\"margin-top: 4px; font-family: inherit;\">Translated/ Published Mark Manson\'s \"The Subtle Art of not giving a F*ck\" and Eric Weiner\'s \"The Geography of Bliss\" into Myanmar in 2018 Director of Innwa Books and Cafe and Zit Myit publishing.</div></div></div><div class=\"_5aj7 _3-8j\" style=\"display: flex; margin: 12px; font-family: system-ui, -apple-system, system-ui, &quot;.SFNSText-Regular&quot;, sans-serif; color: rgb(28, 30, 33); font-size: 12px;\"></div>'),
                array(7, '/storage/author/akyitaw.jpg', 'အကြည်တော်', 'Yangon', 'akyitaw@gmail.com', 'Male', '1963-12-01', 'asdfasdfasfasdfasdfasdfasdf')     
        ];

        foreach ($authors as $author) {
            DB::table('authors')->insert([
                'name' => $author[2],
                'gender'=> $author[5],
                'photo' => $author[1],
                'bio' => $author[7],
                'dob' => $author[6],
                'nationality' => 'Burma',            
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

    }
}
